const mongoose = require('mongoose');

const routeSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
        trim: true
    },
    // Updated to handle the Object we are sending from Swagger
    startLocation: {
        type: {
            type: String,
            enum: ['Point'],
            default: 'Point'
        },
        coordinates: {
            type: [Number], // Format: [Longitude, Latitude]
            required: true
        },
        address: String 
    },
    // Updated to handle the Object we are sending from Swagger
    endLocation: {
        type: {
            type: String,
            enum: ['Point'],
            default: 'Point'
        },
        coordinates: {
            type: [Number],
            required: true
        },
        address: String
    },
    // Added to store the path generated by OpenRouteService
    pathCoordinates: [{
        _id: false,
        lng: Number,
        lat: Number
    }], 
    distance: { type: Number, required: true },
    ecoScore: { type: Number, required: true, min: 1, max: 10 }
}, {
    timestamps: true
});

routeSchema.index({ startLocation: '2dsphere' });

module.exports = mongoose.model('Route', routeSchema);